---
# file: roles/node_common/tasks/disable-firewalld.yml


  - name: be sure autofs is installed 
    yum: 
       name: ['autofs', 'libnfsidmap', 'nfs-utils']
       state: installed 

  - name: Create /homenfs if it doesnt exist 
    file:
      path: /homenfs
      state: directory
      mode: '0755'

  - name: Insert home mounts to auto.master
    lineinfile:
      path: /etc/auto.master
      line: "{{ item.line }}"
    with_items:
      - { line: '/homenfs /etc/auto.homenfs' }

  - name: Create auto.homenfs
    lineinfile:
      path: /etc/auto.homenfs
      line:  '* -fstype=nfs4,nfsvers=4.1,sec=sys wopr:/mnt/drobo2/home/&'
      create: yes


  - name: autofs - enable and start service
    systemd:
       enabled: yes
       state: started
       name: autofs

