---
# tasks file for common

  - name: Add servers to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
      line: "{{ item.line }}"
    with_items:
      - { line: '192.168.1.146   firefly openstack' }
      - { line: '192.168.1.147   reaver' }
      - { line: '192.168.1.128   wopr' }
      - { line: '192.168.1.144   gunstar ansible' }
      - { line: '192.168.1.145    nostromo' }
    tags:
      - etchosts

  - import_tasks: enable-ntp.yml
    tags:
      - enable-ntp

  - import_tasks: ldap-client.yml
    tags:
      - ldap-client

  - import_tasks: autofs.yml
    tags:
      - autofs

  - name: Copy set-prompt.sh into place
    copy:
      src: set-prompt.sh
      dest: /etc/profile.d/set-prompt.sh
      owner: root
      group: root
      mode: 0644

  - import_tasks: extra_packages.yml
    tags:
      - extra_packages
